# --- basics ---
title: "Alessandra Learmount — PhD"
name: "Alessandra Learmount"
description: "About, CV, projects, and contact."
url: "https://alessarndra.github.io"   # or custom domain later
baseurl: "/Alessandra"                               # "" for user site; "/REPO-NAME" for project site

# --- theme & look ---
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "blue"   # clean, bright, professional. Try "air" or "contrast" if you prefer.

logo: "/assets/images/portrait.jpg"   # shows in header

# --- defaults so the sidebar profile appears on pages by default ---
defaults:
  - scope: { path: "" }
    values:
      layout: single
      author_profile: true        # <- turns on the sidebar profile
      toc: true
      toc_sticky: true
      classes: wide

# --- sidebar profile content ---
author:
  name: "Alessandra Learmount"
  avatar: "/assets/images/portrait.jpg"
  bio: "Incoming PhD candidate (Pathology), University of Cambridge."
  location: "Cambridge, UK"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:YOUR-EMAIL"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://uk.linkedin.com/in/alessandralearmount"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/alessarndra"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

og_image: "/assets/images/og-image.jpg"

# (optional) exclude housekeeping files from build
exclude: [README.md, node_modules, vendor]
