title: "Alessandra Learmount — PhD"
name: "Alessandra Learmount"
description: "About, CV, research, and contact."
url: "https://alessarndra.github.io"   # or your custom domain later
baseurl: ""                               # keep "" if this repo is YOUR-USERNAME.github.io

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "aqua"   # nice colour; try "air", "contrast", or "dark" too
logo: "/assets/images/portrait.jpg"

# Nice defaults for clean, pro pages
defaults:
  - scope: { path: "" }
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      classes: wide

# Sidebar profile
author:
  name: "Alessandra Learmount"
  avatar: "/assets/images/portrait.jpg"
  bio: "Incoming PhD candidate (Pathology), University of Cambridge."
  location: "Cambridge, UK"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:al2122@cam.ac.uk"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://uk.linkedin.com/in/alessandralearmount"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

og_image: "/assets/images/og-image.jpg"
exclude: [README.md, node_modules, vendor]
