# --- basics ---
title: "Alessandra Learmount — PhD"
description: "Personal site"
url: "https://alessarndra.github.io"   # or custom domain later
baseurl: "/Alessandra"                               # "" for user site; "/REPO-NAME" for project site


# Use ONE theme only: Minimal Mistakes via remote_theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# REMOVE any line like: theme: jekyll-theme-primer

# Minimal Mistakes basic config (optional but tidy)
minimal_mistakes_skin: "default"
locale: "en-GB"

# Expose the _pages directory as a collection so Jekyll outputs it
collections:
  pages:
    output: true
    permalink: /:name/

# Make sure GitHub Pages loads the approved plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Navigation lives in _data/navigation.yml (see below)

collections:
  pages:
    output: true
    permalink: /:name/

navigation:
  main:
    - title: "About"
      url: /about/
    - title: "CV"
      url: /cv/
    - title: "Research"
      url: /research/
    - title: "Projects"
      url: /projects/
    - title: "Contact"
      url: /contact/

logo: "/assets/images/portrait.jpg"   # shows in header

# --- defaults so the sidebar profile appears on pages by default ---
defaults:
  - scope: { path: "" }
    values:
      layout: single
      author_profile: true        # <- turns on the sidebar profile
      toc: true
      toc_sticky: true
      classes: wide

# --- sidebar profile content ---
author:
  name: "Alessandra Learmount"
  avatar: "/assets/images/portrait.jpg"
  bio: "Incoming PhD candidate (Pathology), University of Cambridge."
  location: "Cambridge, UK"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:YOUR-EMAIL"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://uk.linkedin.com/in/alessandralearmount"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/alessarndra"

og_image: "/assets/images/og-image.jpg"

# (optional) exclude housekeeping files from build
exclude: [README.md, node_modules, vendor]
